travis:
  secure:
    BINSTAR_TOKEN: exkRFmq4KXaXu9E2ke6Y5MFhUizb7rumcXix042Y99qdAGFrIgEgrCud5O4aGKGLcpH5UB7iLUK6k/YCJBg+rFgzbJKccQX/as71bKw2IbSVnLGGddAtjWJznPZWooeR0+OUBOUmSt0HKGn0Qp9KIRREAOrqAcCeTYZluCAEwykoeC4SHMU01X9GGXZTIIpWHIpz/bU+BQBcrwETxz4MP7QcbVeMA2GFoNsHzWA9xB1ZpH4opHJWvaCQYoT+y4Nb/xQRqPg5/seWK0rJBV+DMDqqYUD6CjWi27Sj/8sM+Ra2w6x/hHF56YNmRK6KFlrjoE8vb74sSb2yRmTd6KT+i1b4EW/f8SdIzPjxId5otwX/djW/ETBPf60MHP1mR9kYbYMx7amtba1rV/VOJvfi4wTteXyyjMzEzghrvvSWHeRijkCapxF8mLPDccvYFHgM/Kp1PPc2laZq9c9DNBPKU345kUQCI9ylrh0YzS0VTADrBm9bvPJwt7fkJ/FhuM6+mwA0VBjZyGygzN4epCsq+x5ehUZF4qQ0O8F6SW9F1oGxh/3Hx98gc+JQXAqabZogIsiM1FQEXbStTJvxVm093LvD786h10TQdH7Lyv+PW5CaroUao6KHh1rnPFQvJL0u4OSU2/hGg9YBl+tDkPTD3n+bgR2k5VbDP1PbFH3ogWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
