travis:
  secure:
    BINSTAR_TOKEN: O57cbkApYSzMszT98Lr0RjlJYOJkwe2i3XrMJl864EQpBnTUder61Ygdb9bmKgcTd+WcTXMKHnEyLUojkMH/l9YjhQQVfccCFzrdMMgPJ+9ts0LjRXhHUKzCo+PHREIWUeAeZfUr3qYQnXeUyFJBusgGV7POIiXu7R7AhOprOgZ/aBS/JWy6yEi/l1J+cxLMgFpLstLYbqekwsHX4ggEDN3iVnjlgtBr83Z8MsILblQ8gzqG8CP70K+K272W2OYrZq6Ocbndi47E6CtDwCH/fLYIJS4PBkGvxri/QiH60UQm1rrCY7ODz+P0q65VWc10qh/hj2u/RvjJcBHoOkr9fSIKO6OoSwPMVTUGWk4GDB9YpYgFmTrBFhduKGUpaYul2aK4S7L7VJr6xOP2UzIQudRgWosakWOWe0fejk/Rhc3A/X/bGV3OjgZt6pFPDBnZFShU5LDZtTvkOPe2BZNYXsMGaTuRBO2WU5jV9MB77gaR4o5RCJJE0Wq2+U/+hn8SGUto2uBx5zhFEcvzYizL/CRGZ8PcqAJkOgvn7XbxluIVlPtSVnACoWnKcZU+sb7lTsmH297RsJCOB/vKkuQfHSIsqUk5rzCRiB1nkuH6AC+djjGRnevTFmcNS8aihpvDi/Juf6ft1efGJydPpIoTGnTNuXW9ZTdq8vuVek7OjJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
